# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.26.0
# source: pg_misc.sql
from typing import Any

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


PG_ADVISORY_XACT_LOCK = """-- name: pg_advisory_xact_lock \\:exec
SELECT pg_advisory_xact_lock(:p1)
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def pg_advisory_xact_lock(self, *, key: int) -> None:
        self._conn.execute(sqlalchemy.text(PG_ADVISORY_XACT_LOCK), {"p1": key})


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def pg_advisory_xact_lock(self, *, key: int) -> None:
        await self._conn.execute(sqlalchemy.text(PG_ADVISORY_XACT_LOCK), {"p1": key})
