name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3

      - name: Rye setup
        run: rye sync

      - name: Format check
        run: rye fmt --check

      - name: Lint
        run: rye lint

      - name: Typecheck
        run: make typecheck

      - name: Build
        run: rye build

      - name: Test
        run: rye test
